<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
# Data Science Academy
# Fundamentos de Linguagem Python - Do Básico a Aplicações de IA
# Lista 4 de Exercícios

In [218]:
# Imports
import pandas as pd
import numpy as np

#### Exercício 1: Seleção de Dados Condicional

A partir do DataFrame de funcionários abaixo, selecione e exiba apenas os funcionários do departamento de 'Vendas' que têm um salário superior a R$ 4.500.

In [219]:
# Dados de exemplo
dados = {
    "Nome": ["Ana", "Bruno", "Carla", "Matias", "Eliana", "Fabiano"],
    "Departamento": ["RH", "Vendas", "TI", "Vendas", "RH", "Vendas"],
    "Salário": [4000, 5000, 6200, 4400, 4300, 5500],
}

In [220]:
# DataFrame
df_funcionarios = pd.DataFrame(dados)

In [221]:
df_funcionarios

      Nome Departamento  Salário
0      Ana           RH     4000
1    Bruno       Vendas     5000
2    Carla           TI     6200
3   Matias       Vendas     4400
4   Eliana           RH     4300
5  Fabiano       Vendas     5500

In [222]:
# Solução
func_vendas_maior_4500 = df_funcionarios[
    (df_funcionarios["Departamento"] == "Vendas") & (df_funcionarios["Salário"] > 4500)
]
func_vendas_maior_4500

      Nome Departamento  Salário
1    Bruno       Vendas     5000
5  Fabiano       Vendas     5500

#### Exercício 2: Agrupamento e Agregação (groupby)

Com o DataFrame de vendas abaixo, calcule o total de vendas (Valor) para cada categoria de produto.

In [223]:
# Dados de exemplo
dados_vendas = {
    "Categoria": [
        "Eletrônicos",
        "Vestuário",
        "Eletrônicos",
        "Casa",
        "Vestuário",
        "Eletrônicos",
    ],
    "Produto": ["TV", "Camiseta", "Notebook", "Sofá", "Calça", "Celular"],
    "Valor": [2500, 80, 4500, 1500, 120, 3000],
}

In [224]:
# DataFrame
df_vendas = pd.DataFrame(dados_vendas)

In [225]:
df_vendas

     Categoria   Produto  Valor
0  Eletrônicos        TV   2500
1    Vestuário  Camiseta     80
2  Eletrônicos  Notebook   4500
3         Casa      Sofá   1500
4    Vestuário     Calça    120
5  Eletrônicos   Celular   3000

In [226]:
# Solução
df_vendas.groupby("Categoria")[["Valor"]].sum()

             Valor
Categoria
Casa          1500
Eletrônicos  10000
Vestuário      200

#### Exercício 3: Criação de Nova Coluna
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
A partir do DataFrame de produtos abaixo, crie uma nova coluna chamada Preco_com_Desconto que contenha o valor da coluna Preco com 10% de desconto.

In [227]:
# Dados de exemplo
dados_produtos = {
    "Produto": ["Monitor", "Teclado", "Mouse", "Webcam"],
    "Preco": [800, 120, 70, 250],
}

In [228]:
# DataFrame
df_produtos = pd.DataFrame(dados_produtos)

In [229]:
df_produtos

   Produto  Preco
0  Monitor    800
1  Teclado    120
2    Mouse     70
3   Webcam    250

In [230]:
# Solução
df_produtos["Preco_com_Desconto"] = df_produtos["Preco"] * 0.90
df_produtos

   Produto  Preco  Preco_com_Desconto
0  Monitor    800               720.0
1  Teclado    120               108.0
2    Mouse     70                63.0
3   Webcam    250               225.0

#### Exercício 4: Tratamento de Dados Ausentes (NaN)

No DataFrame de alunos abaixo, substitua as notas ausentes (NaN) pela média da turma (média da coluna 'Nota').

In [231]:
# Dados de exemplo
dados_alunos = {
    "Aluno": ["Alice", "Bernardo", "Clara", "Marcelo"],
    "Nota": [8.5, 7.0, np.nan, 9.0],
}

In [232]:
# DataFrame
df_alunos = pd.DataFrame(dados_alunos)

In [233]:
df_alunos

      Aluno  Nota
0     Alice   8.5
1  Bernardo   7.0
2     Clara   NaN
3   Marcelo   9.0

In [234]:
# Solução
df_alunos.fillna(round(df_alunos["Nota"].mean(), 2), inplace=True)

      Aluno  Nota
0     Alice  8.50
1  Bernardo  7.00
2     Clara  8.17
3   Marcelo  9.00

#### Exercício 5: Ordenação de Dados (sort_values)

Ordene o DataFrame de pontuações abaixo, do maior para o menor com base na coluna 'Pontos' e exiba o resultado.

In [235]:
# Dados de exemplo
dados_pontuacao = {
    "Jogador": ["J1", "J2", "J3", "J4", "J5"],
    "Pontos": [88, 95, 74, 102, 95],
}

In [236]:
# DataFrame
df_pontuacao = pd.DataFrame(dados_pontuacao)

In [237]:
df_pontuacao

  Jogador  Pontos
0      J1      88
1      J2      95
2      J3      74
3      J4     102
4      J5      95

In [238]:
# Solução
df_pontuacao.sort_values(by="Pontos", ascending=False, inplace=True, ignore_index=True)
df_pontuacao

  Jogador  Pontos
0      J4     102
1      J5      95
2      J2      95
3      J1      88
4      J3      74

#### Exercício 6: Combinação de DataFrames (merge)

Combine os DataFrames df_clientes e df_pedidos com base na coluna em comum ID_Cliente.

In [239]:
# Dados de exemplo
df_clientes = pd.DataFrame(
    {"ID_Cliente": [1, 2, 3], "Nome": ["Carlos", "Mariana", "Lucas"]}
)
df_clientes

   ID_Cliente     Nome
0           1   Carlos
1           2  Mariana
2           3    Lucas

In [240]:
# Dados de exemplo
df_pedidos = pd.DataFrame(
    {
        "ID_Pedido": [101, 102, 103],
        "ID_Cliente": [2, 1, 2],
        "Produto": ["Livro", "Caneta", "Caderno"],
    }
)
df_pedidos

   ID_Pedido  ID_Cliente  Produto
0        101           2    Livro
1        102           1   Caneta
2        103           2  Caderno

In [241]:
# Solução
df_novo = df_pedidos.merge(df_clientes, on="ID_Cliente")
df_novo

   ID_Pedido  ID_Cliente  Produto     Nome
0        101           2    Livro  Mariana
1        102           1   Caneta   Carlos
2        103           2  Caderno  Mariana

#### Exercício 7: Manipulação de Strings (.str)
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
No DataFrame abaixo, extraia o ano da coluna Data e crie uma nova coluna chamada Ano.

In [242]:
# Dados de exemplo
dados_eventos = {
    "Evento": ["Conferência A", "Workshop B", "Feira C"],
    "Data": ["2025-10-25", "2026-03-12", "2026-09-01"],
}

In [243]:
# DataFrame
df_eventos = pd.DataFrame(dados_eventos)

In [244]:
df_eventos

          Evento        Data
0  Conferência A  2025-10-25
1     Workshop B  2026-03-12
2        Feira C  2026-09-01

In [245]:
# Solução
df_eventos["Data"] = pd.to_datetime(df_eventos["Data"])

In [246]:
df_eventos.info()

<class 'pandas.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Evento  3 non-null      str
 1   Data    3 non-null      datetime64[us]
dtypes: datetime64[us](1), str(1)
memory usage: 180.0 bytes

In [247]:
df_eventos["Ano"] = df_eventos["Data"].dt.year

In [248]:
df_eventos

          Evento       Data   Ano
0  Conferência A 2025-10-25  2025
1     Workshop B 2026-03-12  2026
2        Feira C 2026-09-01  2026

#### Exercício 8: Uso do Método apply

Crie uma nova coluna Status no DataFrame de notas. Se a Nota for maior ou igual a 7, o status deve ser 'Aprovado', caso contrário, 'Reprovado'. Use o método apply.

In [253]:
# Dados de exemplo
dados_notas = {
    "Aluno": ["Maria", "Jeremias", "Paulo", "Roberto"],
    "Nota": [9.5, 6.0, 5.5, 8.0],
}

In [254]:
# DataFrame
df_notas = pd.DataFrame(dados_notas)

In [255]:
df_notas

      Aluno  Nota
0     Maria   9.5
1  Jeremias   6.0
2     Paulo   5.5
3   Roberto   8.0

In [ ]:
# Solução
df_notas["Status"] = df_notas["Nota"].apply(lambda x:  "Aprovado" if x >= 7 else "Reprovado" )

In [257]:
df_notas

      Aluno  Nota     Status
0     Maria   9.5   Aprovado
1  Jeremias   6.0  Reprovado
2     Paulo   5.5  Reprovado
3   Roberto   8.0   Aprovado

#### Exercício 9: Criação de Tabela Dinâmica (pivot_table)
<!-- Trabalho Desenvolvido na Data Science Academy - www.datascienceacademy.com.br -->
Crie uma tabela dinâmica que mostre a soma das Vendas por Regiao e Vendedor.

In [ ]:
# Dados de exemplo
dados_regional = {
    "Regiao": ["Norte", "Sul", "Norte", "Sul", "Norte", "Sul"],
    "Vendedor": ["Ana", "Bruno", "Ana", "Carlos", "Carlos", "Bruno"],
    "Vendas": [1000, 1500, 1200, 1800, 800, 1300],
}

In [ ]:
# DataFrame
df_regional = pd.DataFrame(dados_regional)

In [ ]:
df_regional

  Regiao Vendedor  Vendas
0  Norte      Ana    1000
1    Sul    Bruno    1500
2  Norte      Ana    1200
3    Sul   Carlos    1800
4  Norte   Carlos     800
5    Sul    Bruno    1300

In [ ]:
# Solução

#### Exercício 10: Análise de Séries Temporais

A partir do DataFrame de visitas a um site, selecione e exiba apenas os registros do mês de agosto de 2026.

In [ ]:
# Dados de exemplo
datas = pd.to_datetime(pd.date_range(start="2026-07-25", periods=15, freq="D"))
dados_visitas = {
    "Visitas": [
        150,
        165,
        178,
        199,
        205,
        210,
        225,
        230,
        215,
        240,
        255,
        260,
        245,
        250,
        270,
    ]
}
df_visitas = pd.DataFrame(data=dados_visitas, index=datas)
df_visitas.index.name = "Data"

In [ ]:
df_visitas

            Visitas
Data
2026-07-25      150
2026-07-26      165
2026-07-27      178
2026-07-28      199
2026-07-29      205
2026-07-30      210
2026-07-31      225
2026-08-01      230
2026-08-02      215
2026-08-03      240
2026-08-04      255
2026-08-05      260
2026-08-06      245
2026-08-07      250
2026-08-08      270

In [ ]:
# Solução

# Fim